name: 📅▶ Update Events from Google Calendar

on:
  schedule:
    - cron: '0 6 * * *'  # Run at midnight CST (6 AM UTC)
  workflow_dispatch:     # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install ics-to-json
        run: |
          npm install -g ics-to-json
          echo "$(npm bin -g)" >> $GITHUB_PATH

      - name: Convert .ics to JSON
        run: |
          curl -s "https://calendar.google.com/calendar/ical/c_dd5b9f0b9b6887c36cde8da86ef9282654e82998c89b4787cc8100fb65dc225e%40group.calendar.google.com/public/basic.ics" -o calendar.ics
          ics-to-json calendar.ics > data/events.json

      - name: Commit only if changed
        run: |
          if ! git diff --quiet data/events.json; then
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add data/events.json
            git commit -m "Update events from Google Calendar"
            git push
          else
            echo "No changes to commit."
          fi

