name: 📅▶ Update Events from Google Calendar

on:
  schedule:
    - cron: '0 6 * * *'  # Run at midnight CST (6 AM UTC)
  workflow_dispatch:     # Allow manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    outputs:
      events_changed: ${{ steps.detect_changes.outputs.events_changed }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install node-ical
        
      - name: Download calendar
        run: curl -s "https://calendar.google.com/calendar/ical/c_dd5b9f0b9b6887c36cde8da86ef9282654e82998c89b4787cc8100fb65dc225e%40group.calendar.google.com/public/basic.ics" -o calendar.ics

      - name: Convert ICS to JSON
        run: node scripts/convert-ics-to-json.js

      - name: Check for changes
        id: detect_changes
        run: |
          if ! git diff --quiet data/events.json; then
            echo "events_changed=true" >> $GITHUB_OUTPUT
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add data/events.json
            git commit -m "Update events from Google Calendar"
            git push
          else
            echo "events_changed=false" >> $GITHUB_OUTPUT
            echo "No changes to commit."

  trigger-hugo:
    name: Trigger Hugo Build
    needs: update
    if: ${{ needs.update.outputs.events_changed == 'true' }}
    uses: ./.github/workflows/hugo-build.yaml
    with:
      triggeredByEventChange: true

    
