name: 🔁 Weekly Leadership Standup

on:
  workflow_dispatch:

  schedule:
    - cron: '0 13 * * 1'

jobs:
  check-repo:
    runs-on: ubuntu-latest
    outputs:
        is-official: ${{ steps.set.outputs.is-official }}
    steps:
        -   name: Check if running on stlgamedev/STLGameDevSite
            id: set
            run: |
                if [[ "${GITHUB_REPOSITORY}" == "stlgamedev/STLGameDevSite" ]]; then
                    echo "Running in official repo."
                    echo "is-official=true" >> $GITHUB_OUTPUT
                else
                    echo "⚠️ This workflow runs only on the main stlgamedev/STLGameDevSite repo. Skipping..."
                    echo "is-official=false" >> $GITHUB_OUTPUT
                fi

  message:
    runs-on: ubuntu-latest
    steps:
      - name: Send Message
        run: |
              curl --location 'https://discord.com/api/v10/channels/${{ secrets.STL_LEADERSHIP_CHANNEL }}/messages' \
                  --header 'Content-Type: application/json' \
                  --header 'Accept: application/json' \
                  --header 'Authorization: Bot ${{ secrets.DISCORD_API_TOKEN }}' \
                  --data '{"content":"<@&492511881811197963>: **SHOW ME WHAT YOU GOT!**"}'
